Update Script gtm no load sf

diff --git a/Script gtm no load sf b/Script gtm no load sf
--- a/Script gtm no load sf
+++ b/Script gtm no load sf
@@ -17,13 +17,16 @@ LOOP_DELAY=1  # Set the loop delay to 1 second
 ## Your DNSTT Nameserver & your Domain `A` Record
 
 NS='ns.rico.hashi-rama.com'
-NS1='ns.kaisen.ismaelsakalam.online'
-NS2='ns.rico.hashi-rama.com'
+NS1='geim.vantricks.tech'
+NS2='ns.jerald.acerodns.xyz'
+NS3='ns.kaisen.ismaelsakalam.online'
+NS4='ns.dnstt.palaboy.tech'
+NS5='hp.bisiro.palaboy.tech'
 A='ns.rico.hashi-rama.com'
 
 ## Add your DNS here
 
-declare -a HOSTS=('112.198.115.60' '112.198.115.60' '112.198.115.36' '124.6.181.12' '124.6.181.36' '112.198.115.44' '124.6.181.4' '124.6.181.44')
+declare -a HOSTS=('112.198.115.60' '112.198.115.60' '112.198.115.36' '124.6.181.12' '124.6.181.36' '112.198.115.44' '124.6.181.4' '124.6.181.44' '124.6.181.20' '112.198.111.92' '124.6.180.30' '149.112.124.150')
 
 ## Linux' dig command executable filepath
 ## Select value: "CUSTOM|C" or "DEFAULT|D"
@@ -43,7 +46,7 @@ CUSTOM_DIG=/data/data/com.termux/files/home/go/bin/fastdig
 VER=0.1
 
 # Define text color codes
-PURPLE='\e[35m'
+PINK='\e[38m'
 RED='\e[31m'
 RESET='\e[0m'
 
@@ -64,7 +67,7 @@ fi
 # Function to check DNS resolution and ping DNS nameservers
 check() {
     for host in "${HOSTS[@]}"; do
-        (timeout -k 3 3 ${_DIG} @"$host" "$A" && echo -e "${PURPLE}Host $host: DNS resolution successful.${RESET}") || echo -e "${RED}Host $host: DNS resolution failed.${RESET}"
+        (timeout -k 3 3 ${_DIG} @"$host" "$A" && echo -e "${PINK}Host $host: DNS resolution successful.${RESET}") || echo -e "${RED}Host $host: DNS resolution failed.${RESET}"
     done
 
     # Add DNS nameservers and host IPs to check with ping
@@ -72,7 +75,7 @@ check() {
 
     for target in "${PING_TARGETS[@]}"; do
         if ping -c 1 -W 2 "$target" &>/dev/null; then
-            echo -e "${PURPLE}Ping to $target: Success.${RESET}"
+            echo -e "${GREEN}Ping to $target: Success.${RESET}"
         else
             echo -e "${RED}Ping to $target: Failed.${RESET}"
         fi
